### ISSUE TITLE
301 error when doing a curl on cli.fyi

### ISSUE THREAD

**Issue by VonKavalier** [daveearley/cli.fyi#7]
When I do the `$ curl cli.fyi/BTC` example request, all I get is : 
```html
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.12.1 (Ubuntu)</center>
</body>
</html>
```

I need to pass the `-L` parameter in order to get something.

I think this should be mentioned in the documentation, although it worked without before :confused:

**Comment by daveearley** [comment]
Thanks for bringing this to my attention @VonKavalier! It's related to a bad Nginx update. I'll fix it ASAP.

**Comment by VonKavalier** [comment]
Awesome ! Thanks for the quick reply :)
I'll close it then ;)
